cl/urls.py
from django.urls import path
from . import views

app_name = 'cl'

urlpatterns = [
  path('', views.CalendarView.as_view(), name="calendar"),
  path('event/new/', views.event, name="event_new"),
  path('event/edit/(?<event_id>\d+)/', views.event, name="event_edit"),
  path('eventdelete/<event_id>/', views.EventDelete.as_view(), name="eventdelete"),
  
]

formset/app/urls.py
from django.urls import path 
from . import views 

urlpatterns = [
  path('', views.make_test_modelformset, name="formset"),
  
]

formset/pj_formset/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

pj_cl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cl.urls')),
]

cl/models.py
from django.db import models
from django.urls import reverse


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('cl:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'

formset/app/models.py
from django.db import models

# Create your models here.

class TestModel(models.Model):
    text = models.CharField(max_length=20)

cl/forms.py
from django.forms import ModelForm, DateInput
from .models import Event

class EventForm(ModelForm):
    class Meta:
        model = Event

        widgets = {
          'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
          'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EventForm,self).__init__(*args, **kwargs)

        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

formset/app/forms.py
from django import forms

cl/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.utils.safestring import mark_safe

import calendar
from .models import Event
from .utils import Calendar
from .forms import EventForm

class CalendarView(generic.ListView):
    model = Event
    template_name = 'cl/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' +str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' +str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
       instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cl:calendar'))
    return render(request, 'cl/event.html', {'form': form, 'event_id': event_id})


class EventDelete(generic.DeleteView):
    model = Event
    context_object_name = 'event'
    success_url = reverse_lazy('cl:calendar')

formset/app/views.py
from django.shortcuts import render
from .models import TestModel
from django import forms
from django.http import HttpResponse

# Create your views here.

def make_test_modelformset(request):
    TestModelFormSet = forms.modelformset_factory(
      model = TestModel,
      fields  =('text',),
      extra=3,
    )
    if request.method == 'POST':
        formset = TestModelFormSet(request.POST,queryset=TestModel.objects.none())
        if formset.is_valid():
            formset.save()

            data = [x.text for x in TestModel.objects.all()]
            return HttpResponse(repr(data))
    else:
        formset = TestModelFormSet(queryset=TestModel.objects.none())
    return render(request, 'app/form1.html', {'formset': formset})

cl/templates/cl/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'cl/css/styles.css'%}" type="text/css">

    <title>calendar</title>
  </head>
  <body>
    <h1 class="title">{% block title %}{% endblock %}</h1>
    <hr>

    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
 
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock %}
  </body>
</html>

cl/templates/cl/calendar.html
{% extends 'cl/base.html' %}
{% block title %}
Calendar
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cl:calendar' %}?{{prev_month}}">Previos Month</a>
  <a class="btn btn-info right" href="{% url 'cl:calendar' %}?{{next_month}}">Next Month</a>
  <a class="btn btn-info right" href="{% url 'cl:event_new' %}">New Event</a>
</div>

{{calendar}}
{% endblock %}

cl/templates/cl/event.html
{% extends 'cl/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a  href="{% url 'cl:calendar' %}"><div class="btn btn-info left">Calendar</div></a>
</div>

{% if form.errors %}
{% for field in form %}
  {% for error in field.errors %}
   <div class="alert alear-danger">
     {{ field.label }}<strong>{{ error|escape }}</strong>
   </div>
  {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    {{ field.label }}<strong>{{ error|escape }}</strong>
  </div>
  {% endfor %}
{% endif %}

<form action="" method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{form}}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right">Submit</button></td>
    </tr>
  </table>
  <a href="{% url 'cl:eventdelete' pk=event_id %}"><button type="submit" class="btn btn-info right">削除</button></a>
</form>
{% endblock %}

cl/templates/cl/event_confirm_delete.html
{% extends 'cl/base.html' %}
<form action="" method="post">
  {% csrf_token %}
  <p>本当に{{event}}を削除しますか？</p>
  <input type="submit" value="削除">
</form>

formset/app/templates/app/form1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="main">
    <form action="" method="post">
      {% csrf_token %}
      {% for formset in formset %}
      {{formset.text}}
      <input type="submit" value="追加">
      {% endfor %}
    </form>
  </div>
</body>
</html>

<form action="" method="post">
  {% csrf_token %}
  {{formset}}
  <input type="submit" value="作成">
</form>